### ISSUE TITLE
Unit testing framework

### ISSUE THREAD

**Issue by zachallaun** [recursecenter/webstack.jl#18]
It would be awesome if someone would take a day or two to create something simple so that we can start building a test suite.

**Comment by chuckha** [comment]
Agreed, a lack of a test suite makes me sad.

**Comment by chuckha** [comment]
agreed, this would be useful

**Comment by chuckha** [comment]
Disocvered! Although, I don't understand why test_fails raises an error if you give it a false expression.

``` .jl
module MyMath

using Test

function add(a::Number, b::Number)
    a + b
end

@test add(1, 2) == 3
@test add(-13, 8) == -5
@test add(100, 0) == 100

# Why does this raise an error?
#@test_fails add(1, 5) 5

@test_approx_eq add(1.00000000000001, 2.) 3
@test_approx_eq_eps add(1.1, 2.) 3 .11

end # end module
```

**Comment by zachallaun** [comment]
I've wrapped `Base.Test` in what I think is a nicer syntax, along with a simple runner.

Clone [defacto](https://github.com/zachallaun/defacto) and run `julia test_defacto.jl` to see example output. It's pretty rough right now… I need to find a way to display line numbers, etc. May require rewriting some stuff from `Base.Test` that I'm currently building on.

**Comment by despeset** [comment]
[DeFacto](https://github.com/zachallaun/defacto) closes this ticket.
