### ISSUE TITLE
URL parameter parsing

### ISSUE THREAD

**Issue by despeset** [recursecenter/webstack.jl#29]
URL variables should be parsed out of the request and an interface for accessing them should be exposed

**Comment by zachallaun** [comment]
Isn't this covered by #25? ("named wildcards")

**Comment by despeset** [comment]
No, I mean like this `/foo/bar?a=1&b=2`

**Comment by despeset** [comment]
So Chuck and I decided this should just be in `RequestParser.jl` because there's really no case where we don't want to be pulling these values out of `Request.resource`.  

Retagged to `http 1.1` from `meddle`

**Comment by despeset** [comment]
This was closed by #30
