### ISSUE TITLE
Meddle File Server should not let requests escape the directory

### ISSUE THREAD

**Issue by astrieanna** [recursecenter/webstack.jl#37]
So, run `julia ./example/meddle.jl`.
Then `curl localhost:8000/../../../../../../bin/ls` or `curl localhost:8000/../julia/README.md`, for example.

Basically, you are serving _all the files on your computer_ to anyone who can guess the paths.
I'm assuming the intention is to trap the file paths to being within the directory passed to the fileserver  MidWare in its constructor.

This would get worse if you were generating pages to display for folders (as in, with links to file pages), since then you could basically run `ls` on the server running the file server, too -- which makes guessing a lot easier.

**Comment by despeset** [comment]
Yeah this is bad.

**Comment by zachallaun** [comment]
What are you talking about? This is an incredible feature!
