### ISSUE TITLE
Chat example should escape input.

### ISSUE THREAD

**Issue by astrieanna** [recursecenter/webstack.jl#54]
We should not broadcast arbitrary html/css/javascript to other users browsers.

This allows for arbitrary html (including marquees of auto-playing youtube videos), and apparently javascript as well.

**Comment by despeset** [comment]
Hmm... sure does.  We're going to have to write some robust escaping code for this and #53

**Comment by despeset** [comment]
This is fixed, but the example isn't in any active repo any more.  We should discuss exactly where to put that stuff.
