### ISSUE TITLE
Web App outide of webstack.jl folder

### ISSUE THREAD

**Issue by astrieanna** [recursecenter/webstack.jl#55]
I should be able to write a web application depending on webstack.jl _outside_ of the webstack.jl folder.
Currently, when I move any of the examples out of the webstack.jl folder, they no longer work because they can't find Http.

This would be solved by moving the pieces of webstack.jl into packages.

**Comment by despeset** [comment]
Agreed! I'm working on this today.

**Comment by astrieanna** [comment]
Maybe webstack.jl can be as quick at fixing bugs at Julia core! :P

**Comment by despeset** [comment]
Closed by dea5d82801e58b741ecf78495ec3c1aa2e5f1e73
